# Generated by Django 5.2.8 on 2025-11-16 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('linkedin_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=50, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('applicants_count', models.IntegerField(blank=True, null=True)),
                ('company_logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('search_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('search_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_id'], name='jobs_joblis_job_id_db5b1a_idx'), models.Index(fields=['title'], name='jobs_joblis_title_da092b_idx'), models.Index(fields=['company_name'], name='jobs_joblis_company_e94c9f_idx'), models.Index(fields=['location'], name='jobs_joblis_locatio_6129f1_idx'), models.Index(fields=['-created_at'], name='jobs_joblis_created_f9b3ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('experience_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('total_results', models.IntegerField(default=0)),
                ('results_fetched', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['keyword', 'location'], name='jobs_jobsea_keyword_bf0695_idx'), models.Index(fields=['-created_at'], name='jobs_jobsea_created_bdb4c3_idx')],
            },
        ),
    ]
