# Generated by Django 5.2.8 on 2025-11-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='is_enriched',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
