# Generated by Django 5.2.8 on 2025-11-19 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joblisting_is_enriched'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('job_location', models.CharField(blank=True, max_length=500, null=True)),
                ('job_url', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the application', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.joblisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['user', '-applied_at'], name='jobs_jobapp_user_id_a69614_idx'), models.Index(fields=['-applied_at'], name='jobs_jobapp_applied_ab7064_idx'), models.Index(fields=['company_name'], name='jobs_jobapp_company_59692b_idx')],
            },
        ),
    ]
