# Generated by Django 5.2.8 on 2025-11-19 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('job_listing__isnull', False)), fields=('user', 'job_listing'), name='unique_user_job_listing'),
        ),
    ]
