# Generated by Django 5.2.8 on 2025-11-21 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication_unique_user_job_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('declined', 'Declined'), ('phone_screening', 'Phone Screening'), ('first_round', 'First Round'), ('second_round', 'Second Round'), ('third_round', 'Third Round'), ('offer', 'Offer')], db_index=True, default='applied', help_text='Current status of the application', max_length=20),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='jobs_jobapp_status_8c3944_idx'),
        ),
    ]
