# Generated by Django 5.2.8 on 2025-12-05 09:22

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobapplication_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this search profile', max_length=255, null=True)),
                ('keyword', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of job types (full_time, part_time, contract, etc.)', size=None)),
                ('experience_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of experience levels (entry_level, mid_senior_level, etc.)', size=None)),
                ('date_posted', models.CharField(blank=True, help_text='Date posted filter (any_time, past_24_hours, past_week, past_month)', max_length=50, null=True)),
                ('limit', models.IntegerField(default=25, help_text='Maximum number of results to return')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search Profile',
                'verbose_name_plural': 'Search Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='jobs_search_user_id_36d439_idx'), models.Index(fields=['keyword', 'location'], name='jobs_search_keyword_6326f3_idx'), models.Index(fields=['-created_at'], name='jobs_search_created_ca8225_idx')],
            },
        ),
    ]
