# Generated by Django 5.2.8 on 2025-12-05 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchprofile',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='searchprofile',
            name='limit',
        ),
    ]
