# Generated by Django 5.2.8 on 2025-12-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobalert_date_posted_remove_jobalert_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblisting',
            name='is_enriched',
        ),
    ]
