# Generated by Django 5.2.8 on 2025-11-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypstTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('code', models.TextField()),
            ],
            options={
                'verbose_name': 'Typst Template',
                'verbose_name_plural': 'Typst Templates',
                'db_table': 'typst_templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
