# Generated by Django 5.2.8 on 2025-11-18 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentStatus',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='document_status', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('has_uploaded_document', models.BooleanField(default=False)),
                ('last_upload_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Document Status',
                'verbose_name_plural': 'User Document Statuses',
                'db_table': 'user_document_status',
            },
        ),
    ]
